blueprint:
  name: ESPHome 8-Button Controller
  description: Configure actions for an ESPHome device with 8 buttons, supporting single press, double press, and long press actions.
  domain: automation
  input:
    controller_device:
      name: ESPHome Device
      description: The ESPHome device that contains the buttons
      selector:
        device:
          integration: esphome
          
    # Button 1 Configuration
    button_1_entity:
      name: Button 1 Entity
      description: The binary sensor entity representing Button 1
      selector:
        entity:
          domain: binary_sensor
    
    button_1_single_press_action:
      name: Button 1 - Single Press Action
      description: Action to perform when Button 1 is pressed once
      default: []
      selector:
        action: {}
          
    button_1_double_press_action:
      name: Button 1 - Double Press Action
      description: Action to perform when Button 1 is double pressed
      default: []
      selector:
        action: {}
          
    button_1_long_press_action:
      name: Button 1 - Long Press Action
      description: Action to perform when Button 1 is long pressed
      default: []
      selector:
        action: {}

    # Add similar configurations for buttons 2-8...

# Define the triggers for all button events
trigger:
  # Button 1 Triggers
  - platform: state
    entity_id: !input button_1_entity
    to: "on"
    id: button_1_single
  - platform: event
    event_type: esphome.button_double_press
    event_data:
      entity_id: !input button_1_entity
    id: button_1_double
  - platform: event
    event_type: esphome.button_long_press
    event_data:
      entity_id: !input button_1_entity
    id: button_1_long
  
  # Add similar triggers for buttons 2-8...

# Action logic based on which trigger fired
action:
  - choose:
    # Button 1 Actions
    - conditions:
        - condition: trigger
          id: button_1_single
      sequence: !input button_1_single_press_action
    - conditions:
        - condition: trigger
          id: button_1_double
      sequence: !input button_1_double_press_action
    - conditions:
        - condition: trigger
          id: button_1_long
      sequence: !input button_1_long_press_action
    
    # Add similar actions for buttons 2-8...

mode: single
