blueprint:
  name: ESPHome Multi-Click Button
  description: Control actions based on single, double, triple clicks, and hold of an ESPHome button
  domain: automation
  input:
    button_entity:
      name: Button Entity
      description: The ESPHome text sensor that reports button actions
      selector:
        entity:
          domain: text_sensor
    single_click_action:
      name: Single Click Action
      description: Action to perform on single click
      default: []
      selector:
        action: {}
    double_click_action:
      name: Double Click Action
      description: Action to perform on double click
      default: []
      selector:
        action: {}
    triple_click_action:
      name: Triple Click Action
      description: Action to perform on triple click
      default: []
      selector:
        action: {}
    hold_action:
      name: Hold Action
      description: Action to perform when button is held
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input button_entity
    to: "single"
    id: single_click
  - platform: state
    entity_id: !input button_entity
    to: "double"
    id: double_click
  - platform: state
    entity_id: !input button_entity
    to: "triple"
    id: triple_click
  - platform: state
    entity_id: !input button_entity
    to: "hold"
    id: hold

action:
  - choose:
      - conditions:
          - condition: trigger
            id: single_click
        sequence: !input single_click_action
      - conditions:
          - condition: trigger
            id: double_click
        sequence: !input double_click_action
      - conditions:
          - condition: trigger
            id: triple_click
        sequence: !input triple_click_action
      - conditions:
          - condition: trigger
            id: hold
        sequence: !input hold_action
