blueprint:
  name: ESPHome Multi-Click Button
  description: Automate actions based on single, double, triple clicks, and hold events from an ESPHome button.
  domain: automation
  input:
    button_entity:
      name: Button Text Sensor
      description: Select the ESPHome text sensor entity that reports button clicks.
      selector:
        entity:
          domain: text_sensor
    single_click_action:
      name: Single Click Action
      description: Action to run on single click.
      default: []
      selector:
        action: {}
    double_click_action:
      name: Double Click Action
      description: Action to run on double click.
      default: []
      selector:
        action: {}
    triple_click_action:
      name: Triple Click Action
      description: Action to run on triple click.
      default: []
      selector:
        action: {}
    hold_action:
      name: Hold Action
      description: Action to run when button is held.
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input button_entity

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state in ['single', 'double', 'triple', 'hold'] }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'single' }}"
        sequence: !input single_click_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'double' }}"
        sequence: !input double_click_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'triple' }}"
        sequence: !input triple_click_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'hold' }}"
        sequence: !input hold_action

mode: queued
max_exceeded: silent
